### ISSUE TITLE
Error status incorrect

### ISSUE THREAD

**Issue by yonas124** [Hilscher/node-red-contrib-s7comm#2]
I got it working easily so kudos to you but the payload.error is 0 even though I disconnected the plc. It becomes -1 only if I put non-existent address.

**Comment by sembaye** [comment]
Hi,
that's weird. I have done extensive testing with a non-existent PLC. What system do you use? (Windows /Linux)
I have observed once that the TCP stack of node. js reacts differently to the systems. However, this was the case with an earlier version of node. js.

**Comment by yonas124** [comment]
So my setup is:
- Node-red runs on raspberry pi
- IBH S7 softplc runs on my windows 10 PC
- I disconnect by terminating the softplc program

The node actually shows 'disconnected' but the payload.error is still 0 with array of last good values, not null.
I left my raspi at home so I cannot attach the screenshot. I will later.

**Comment by sembaye** [comment]
In version 1.0.2 there is an error when reading an array of values. The error will be fixed in the next version (release date is Friday).
I suggest that you run the test again with the new version.

**Comment by sembaye** [comment]
Hi,
a new version is relesed. Is the issue fixed with this version or still available?

**Comment by sembaye** [comment]
close due to inactivity
