### ISSUE TITLE
Negative float values writing to PLC

### ISSUE THREAD

**Issue by VladislavVelikanov** [Hilscher/node-red-contrib-s7comm#3]
Hi,
My setup is:
-raspberry pi 3 with Node-Red
-Siemens S7-400 CPU (installed on production line)

When i try to write in PLC negative float value( for example -1.2 ) in DataBlock,  I get "0" in PLC.  And at the output message of writing node has "0" in values and no errors.
Reading negative float values from PLC DataBlock is OK.

**Comment by sembaye** [comment]
Fixed in Version 1.1.3.
